export const DONE_LOADING = 'DONE_LOADING';

export const LOAD_SETTINGS = 'LOAD_SETTINGS';
export const LOAD_SETTINGS_SUCCESS = 'LOAD_SETTINGS_SUCCESS';
export const LOAD_SETTINGS_FAILURE = 'LOAD_SETTINGS_FAILURE';

export const SAVE_SETUP_REQUEST = 'SAVE_SETUP_REQUEST';
export const SAVE_SETUP_SUCCESS = 'SAVE_SETUP_SUCCESS';
export const SAVE_SETUP_FAIL = 'SAVE_SETUP_FAIL';

export const UPDATE_SETTINGS_REQUEST = 'UPDATE_SETTINGS_REQUEST';
export const UPDATE_SETTINGS_SUCCESS = 'UPDATE_SETTINGS_SUCCESS';
export const UPDATE_SETTINGS_FAILURE = 'UPDATE_SETTINGS_FAILURE';
