engines:
  eslint:
    enabled: true
ratings:
   paths:
   - client/**
   - shared/**
   - server/**
   - "**.js"
exclude_paths:
  - ./node_modules/**/*
  - boldrCMS/**
  - db/**
  - docs/**
  - bin/**
  - flow-typed/**
  - internal/**
  - shared/**/*.test.js
  - server/**/*.test.js
