engines:
  eslint:
    enabled: true
ratings:
   paths:
   - packages/boldr-cms/src/**
   - packages/boldr-api/src/**
   - "**.js"
exclude_paths:
- **/node_modules/**/*
- packages/boldr-editor
- packages/babel-preset-boldr
- packages/eslint-config-boldr
- packages/boldr-cms/boldr/**
- build/**
- docs/**
- bin/**
- flow-typed/**
- tools/**
- packages/**/*.test.js
