workspace:
  base: /boldr
  path: src/github.com/strues/boldr

clone:
  git:
    image: plugins/git
    depth: 10

pipeline:
  test:
    image: node:7.10
    environment:
      - BOLDR__DB__URL=postgres://postgres:password@database:5432/test
      - BOLDR__REDIS__URL=redis://cache:6379
    commands:
      - yarn install --pure-lockfile
      - sleep 15
      - BOLDR__DB__URL=postgres://postgres:password@database:5432/test yarn run migrate:test
      - BOLDR__DB__URL=postgres://postgres:password@database:5432/test yarn run seed:test
      - BOLDR__DB__URL=postgres://postgres:password@database:5432/test BOLDR__REDIS__URL=redis://cache:6379 yarn run test:ci
services:
  database:
    image: postgres:9.6.3-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test
      - POSTGRES_PASSWORD=password
  cache:
    image: strues/redis:3.2.8-alpine
    expose:
      - "6379"
