pipeline:
  build:
    image: node:8
    commands:
      - yarn install --pure-lockfile
      - yarn test:ci
      - yarn add codecov
      - ./node_modules/.bin/codecov -t a3dc697a-382d-4d84-a07b-1f5682c3d70a -f coverage/coverage-final.json
