language: node_js
node_js:
  - "6.1.0"
sudo: required

services:
  - docker

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
- docker pull strues/rethinkdb
- docker run -d -p 127.0.0.1:28015:28015 strues/rethinkdb
- docker ps -a

before_script:
  - npm run test:api

cache:
  directories:
    - node_modules
