sudo: required

language: node_js

node_js:
  - 7.7

services:
  - docker

branches:
  only:
  - master
  - develop

env:
  CXX: g++-4.8
  TOKEN_SECRET: b0ldrs0s3cr3t
git:
  depth: 3
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - yarn

before_script:
  - yarn build:test

script:
  - yarn test:ci

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  yarn: true
  directories:
    - node_modules
