language: node_js
node_js:
  - "5.1.x"
sudo: false # this enables faster builds - http://docs.travis-ci.com/user/migrating-from-legacy/
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script:
- npm run test:api
