language: node_js
node_js:
  - "6.2.0"
sudo: required

services:
  - postgresql
  - redis-server

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_script:
  - npm run testdb:init
  - npm run migrate

cache:
  directories:
    - node_modules
