version: '2'

services:
  data-volumes:
    image: busybox
    tty: true
    stdin_open: true
    volumes:
    - /data
    - /var/lib/postgresql/data
    - ./backup:/postgresql.backup:z
    command: ["chown", "-v", "-R", "999:999", "/var/lib/postgresql/data"]
  db:
    build: ./tools/postgres
    container_name: postgres
    hostname: postgres1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DBNAME: boldr
      POSTGRES_DBUSER: boldr
      POSTGRES_DBPASS: boldr
    ports:
      - 5432:5432/tcp
    volumes_from:
      - data-volumes
    networks:
      - boldr
  # boldr1:
  #   build: ./
  #   working_dir: /home/app
  #   depends_on:
  #       - db
  #   ports:
  #     - 3000:3000/tcp
  #     - 5858:5858/tcp
  #   networks:
  #     - boldr
networks:
  boldr:
    driver: bridge

  #   networks:
  #     - boldr

# POSTGRES_PORT_5432_TCP_ADDR
# POSTGRES_PORT_5432_TCP_PORT
