version: '3'

services:
  postgres:
    build: ${PWD}/.boldr/docker/postgres
    container_name: postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
    tmpfs:
      - /tmp
      - /var/run/postgresql
    environment:
      POSTGRES_PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - boldr-postgres-data:/var/lib/postgresql/data
    logging:
      options:
        max-size: "50m"
        max-file: "3"
    restart: unless-stopped
  redis:
    image: redis:3.2.10-alpine
    container_name: redis
    restart: unless-stopped
    expose:
      - "6379"
    ports:
      - "6379:6379"
    volumes:
      - boldr-redis-data:/data

volumes:
  boldr-postgres-data:
  boldr-redis-data:
