version: '2'
services:

  datastore:
    image: busybox
    container_name: boldr_data
    tty: true
    stdin_open: true
    volumes:
      ## Redis DB
      - "./.volumes/redis:/data:rw"
      ## Postgres databases
      - "./.volumes/pgdata:/var/lib/postgresql/data:rw"

  postgres:
    container_name: boldr_pg
    image: sameersbn/postgresql:9.5-2
    environment:
      - PG_PASSWORD=password
      - DB_USER=boldr
      - DB_PASS=password
      - DB_NAME=boldr_development,boldr_test,boldr
      - PG_TRUST_LOCALNET=true
    ports:
      - "5432:5432"
    volumes_from:
      - datastore
    networks:
      - boldr

  redis:
    image: redis:3.2.3-alpine
    container_name: boldr_redis
    ports:
      - "6379:6379"
    volumes_from:
      - datastore
    networks:
      - boldr

  # boldr:
  #   image: strues/boldr:0.5.1
  #   container_name: boldr_cms
  #   ports:
  #     - "3000:3000"
  #   volumes_from:
  #     - datastore
  #   links:
  #     - redis
  #     - postgres
  #   networks:
  #     - boldr
  #   environment:
  #     - REDIS_CONN_URI=redis://boldr_redis

networks:
  boldr:
    driver: bridge

volumes:
  datastore:
    driver: local
