version: '2'
services:

  datastore:
    image: busybox
    container_name: boldr_data
    tty: true
    stdin_open: true
    volumes:
      - "./volumes/redis/data:/data:rw"
      - "./tools/docker/postgres/configs:/docker-entrypoint-initdb.d:ro"
      ## NGINX
      - "./volumes/sites:/etc/nginx/sites-enabled:rw"
      - "./volumes/nginx/certs:/etc/nginx/certs:rw"
      - "./volumes/nginx:/etc/nginx:rw"
        ## Web root
      - "./volumes/www:/srv/www:rw"
      ## Postgres databases
      - "./volumes/postgres:/var/lib/postgresql/data:rw"
  # nginx:
  #     build: ./tools/docker/nginx
  #     container_name: nginx
  #     ports:
  #       - "80:80"
  #       - "443:443"
  #     volumes_from:
  #       - datastore

  postgres:
    container_name: boldr_pg
    image: strues/postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=boldr_development
    ports:
      - "5432:5432"
    volumes_from:
      - datastore
    networks:
      - boldr
    # links:
    #   - "boldr-api"

  redis:
    image: strues/redis
    container_name: boldr_redis
    ports:
      - "6379:6379"
    volumes_from:
      - datastore
    networks:
      - boldr
    # links:
    #   - "boldr-api"

networks:
  boldr:
    driver: bridge

volumes:
  datastore:
    driver: local
