version: '2'

services:
  data_store:
    image: busybox
    container_name: boldr-data_store
    tty: true
    stdin_open: true
    volumes:
      - "./docker/volumes/public:/home/boldr-cms/public:rw"
      - "./docker/volumes/redis/data:/data:rw"
      - "./docker/volumes/logs/db:/var/log:rw"
      - "./docker/postgres/configs:/docker-entrypoint-initdb.d:ro"

  # webserver:
  #   image: nginx
  #   ports:
  #     - 80:80
  #     - 443:443
  #   volumes:
  #     - /etc/nginx/conf.d
  #     - /etc/nginx/vhost.d
  #     - /usr/share/nginx/html
  #     - /etc/nginx/certs

  # proxy:
  #   build: ./docker/docker-gen
  #   volumes:
  #     - /var/run/docker.sock:/tmp/docker.sock:ro
  #   volumes_from:
  #     - nginx
  #   command:
  #     - -notify-sighup
  #     - httpd_nginx_1
  #     - -watch
  #     - -only-exposed
  #     - -wait
  #     - 5s:30s
  #     - /etc/docker-gen/templates/nginx.tmpl
  #     - /etc/nginx/conf.d/default.conf

  # letsencrypt:
  #   image: jrcs/letsencrypt-nginx-proxy-companion
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #   volumes_from:
  #     - nginx
  #   environment:
  #     - "NGINX_DOCKER_GEN_CONTAINER=httpd_nginx-gen_1"

  boldr-cms:
    build: ./cms
    container_name: boldr-cms
    command: npm run start:prod
    environment:
      POSTGRES_CONNECTION_URL: postgres://postgres:password@127.0.0.1:5432/boldr_development
    ports:
      - "9221:9221"
    volumes_from:
      - "data_store"

  boldr-api:
    build: ./api
    container_name: boldr-api
    command: npm run start:prod
    environment:
      - database__host=db
      - database__user=postgres
      - database__password=password
      - database__name=boldr_development
      # redis__host: redis_ds

    ports:
      - "9121:9121"

    links:
      - "boldr-cms"
  db:
    container_name: boldr-db
    image: strues/postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      # - POSTGRES_DB
      # - PGDATA="./docker/volumes/db"
    ports:
      - "5432:5432"
    volumes_from:
      - data_store
    networks:
      - boldr
    # links:
    #   - "boldr-api"

  redis_ds:
    build: ./docker/redis
    container_name: boldr-redis
    ports:
      - "6379:6379"
    volumes_from:
      - data_store
    networks:
      - boldr
    # links:
    #   - "boldr-api"

networks:
  boldr:
    driver: bridge

volumes:
  data_store:
    driver: local
