version: '3'

services:
  # proxy:
  #   links:
  #     - cmf
  #     - api
  #   build: ./.boldr/docker/proxy
  #   ports:
  #     - 3000:80

  database:
    build: ./.boldr/db
    restart: always
    container_name: boldr_database
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    volumes:
      - database_volume:/var/lib/postgresql/data/pgdata
    networks:
      - boldr

  redis:
    image: strues/redis:3.2.8-alpine
    container_name: boldr_redis
    restart: always
    read_only: false
    security_opt:
     - "no-new-privileges"
    volumes:
      - redis_volume:/data:rw
    ports:
      - "6379:6379"
    networks:
      - boldr

volumes:
  database_volume: {}
  redis_volume: {}

networks:
  boldr:
    driver: bridge
