version: '2'
services:
  # volumes_source:
  #   image: tianon/true
  #   volumes:
  #     - ${HOST_APP_DIRECTORY}:/var/www/
  # volumes_data:
  #   image: tianon/true
  #   container_name: boldr_data
  #   volumes:
  #     ## Redis DB
  #     - "./.volumes/redis:/data"
  #     ## Postgres databases
  #     - "./.volumes/pgdata:/var/lib/postgresql/data"

  db:
    container_name: boldr_pg
    image: sameersbn/postgresql:9.5-2
    restart: always
    environment:
      - PGDATA=/var/lib/postgresql/data
      - PG_PASSWORD=password
      - DB_USER=boldr
      - DB_PASS=password
      - DB_NAME=boldr
      - PG_TRUST_LOCALNET=true
    ports:
      - "5432:5432"
    volumes:
      - pg_volume:/var/lib/postgresql/data
    networks:
      - boldr

  redis:
    image: redis:3.2.3-alpine
    container_name: boldr_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_volume:/data
    networks:
      - boldr

  api:
    build:
      context: ./api
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
    ports:
      - "2121:2121"
    environment:
      - REDIS_CONN_URI=redis://redis:6379/1
      - POSTGRES_CONN_URI=postgres://boldr:password@db:5432/boldr
    networks:
      - boldr
  # cms:
  #   build:
  #     context: ./cms
  #   depends_on:
  #     - api
  #   links:
  #     - api
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - boldr

networks:
  boldr:
    driver: bridge

volumes:
  pg_volume:
  redis_volume:
