version: '2'

services:
  datastore:
    image: busybox
    container_name: ${PROJECT_ID}-storage
    tty: true
    stdin_open: true
    volumes:
      - "./tools/data:/data:rw"
      - "./tools/data:/data/rethinkdb_data:rw"
      - "./docs/logs/rethinkdb:/var/logs/rethinkdb:rw"
  dbstore:
    image: busybox
    container_name: ${PROJECT_ID}-dbstore
    tty: true
    stdin_open: true
    volumes:
      - "dbstore:/var/lib/postgresql/data"

  redis:
    image: redis:3-alpine
    container_name: ${PROJECT_ID}-redis
    ports:
      - "6379:6379"
    networks:
      - boldr
  postgres:
    image: postgres:9.5
    volumes_from:
          - dbstore
    ports:
      - "5432:5432"
    networks:
      - boldr
    depends_on:
      - dbstore
  # boldr1:
  #   build: ./
  #   depends_on:
  #       - db
  #   ports:
  #     - 3000:3000/tcp
  #     - 5858:5858/tcp
  #   networks:
  #     - boldr
networks:
  boldr:
    driver: bridge

volumes:
  datastore:
    driver: local
  dbstore:
    driver: local
