version: '2'

services:
  data_store:
    image: busybox
    container_name: boldr-data_store
    tty: true
    stdin_open: true
    volumes:
      - "./docker/volumes/public:/home/boldr-cms/public:rw"
      - "./docker/volumes/redis/data:/data:rw"
      - "./docker/volumes/logs/db:/var/log:rw"
      - "./docker/postgres/configs:/docker-entrypoint-initdb.d:ro"

  db:
    container_name: boldr-db
    image: strues/postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      # - POSTGRES_DB
      # - PGDATA="./docker/volumes/db"
    ports:
      - "5432:5432"
    volumes_from:
      - data_store
    networks:
      - boldr
    # links:
    #   - "boldr-api"

  redis_ds:
    build: ./docker/redis
    container_name: boldr-redis
    ports:
      - "6379:6379"
    volumes_from:
      - data_store
    networks:
      - boldr
    # links:
    #   - "boldr-api"

networks:
  boldr:
    driver: bridge

volumes:
  data_store:
    driver: local
