version: '2'

services:
  dbstore:
    image: busybox
    container_name: boldr-dbstore
    tty: true
    stdin_open: true
    volumes:
      - "dbstore:/var/lib/postgresql/data"
      - "./docs/logs/db:/var/log:rw"
      - ./tools/docker/postgres/configs:/docker-entrypoint-initdb.d:ro
  # boldr:
  #   build: .
  #   container_name: boldr
  #   command: npm run start
  #   environment:
  #     POSTGRES_CONNECTION_URL: postgres://postgres:password@db:5432/boldr
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - "./node_modules:/usr/src/boldr/node_modules"
  #     - ".:/usr/src/boldr"
  #   depends_on:
  #     - db
  #     - redis
  #   links:
  #     - "db"
  #     - "redis"
  db:
    container_name: boldr-postgres
    image: strues/postgres
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes_from:
      - dbstore
    networks:
      - boldr
    depends_on:
      - dbstore

  redis:
    image: strues/redis
    container_name: boldr-redis
    ports:
      - "6379:6379"
    volumes:
      - "redisstore:/data"
    networks:
      - boldr

networks:
  boldr:
    driver: bridge

volumes:
  dbstore:
    driver: local
  redisstore:
    driver: local
