// flow-typed signature: 521a063d13e7be89d15774d1bdaa0cc8
// flow-typed version: <<STUB>>/babel-preset-boldr_v^1.1.2/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-boldr'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-boldr' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-preset-boldr/index' {
  declare module.exports: $Exports<'babel-preset-boldr'>;
}
declare module 'babel-preset-boldr/index.js' {
  declare module.exports: $Exports<'babel-preset-boldr'>;
}
