// flow-typed signature: 30f01e0152b6d80dc78322a3f8a7f2e2
// flow-typed version: <<STUB>>/draft-js_v0.9.1/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'draft-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'draft-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'draft-js/Draft' {
  declare module.exports: any;
}

declare module 'draft-js/Draft.min' {
  declare module.exports: any;
}

declare module 'draft-js/adjustBlockDepthForContentState' {
  declare module.exports: any;
}

declare module 'draft-js/applyEntityToContentBlock' {
  declare module.exports: any;
}

declare module 'draft-js/applyEntityToContentState' {
  declare module.exports: any;
}

declare module 'draft-js/AtomicBlockUtils' {
  declare module.exports: any;
}

declare module 'draft-js/BlockMap' {
  declare module.exports: any;
}

declare module 'draft-js/BlockMapBuilder' {
  declare module.exports: any;
}

declare module 'draft-js/BlockTree' {
  declare module.exports: any;
}

declare module 'draft-js/CharacterMetadata' {
  declare module.exports: any;
}

declare module 'draft-js/ComposedEntityMutability' {
  declare module.exports: any;
}

declare module 'draft-js/ComposedEntityType' {
  declare module.exports: any;
}

declare module 'draft-js/CompositeDraftDecorator' {
  declare module.exports: any;
}

declare module 'draft-js/ContentBlock' {
  declare module.exports: any;
}

declare module 'draft-js/ContentState' {
  declare module.exports: any;
}

declare module 'draft-js/ContentStateInlineStyle' {
  declare module.exports: any;
}

declare module 'draft-js/convertFromDraftStateToRaw' {
  declare module.exports: any;
}

declare module 'draft-js/convertFromHTMLToContentBlocks' {
  declare module.exports: any;
}

declare module 'draft-js/convertFromRawToDraftState' {
  declare module.exports: any;
}

declare module 'draft-js/createCharacterList' {
  declare module.exports: any;
}

declare module 'draft-js/decodeEntityRanges' {
  declare module.exports: any;
}

declare module 'draft-js/decodeInlineStyleRanges' {
  declare module.exports: any;
}

declare module 'draft-js/DefaultDraftBlockRenderMap' {
  declare module.exports: any;
}

declare module 'draft-js/DefaultDraftInlineStyle' {
  declare module.exports: any;
}

declare module 'draft-js/DOMDerivedSelection' {
  declare module.exports: any;
}

declare module 'draft-js/Draft' {
  declare module.exports: any;
}

declare module 'draft-js/DraftBlockRenderConfig' {
  declare module.exports: any;
}

declare module 'draft-js/DraftBlockRenderMap' {
  declare module.exports: any;
}

declare module 'draft-js/DraftBlockTag' {
  declare module.exports: any;
}

declare module 'draft-js/DraftBlockType' {
  declare module.exports: any;
}

declare module 'draft-js/DraftDecorator' {
  declare module.exports: any;
}

declare module 'draft-js/DraftDecoratorType' {
  declare module.exports: any;
}

declare module 'draft-js/DraftDragType' {
  declare module.exports: any;
}

declare module 'draft-js/DraftEditor.react' {
  declare module.exports: any;
}

declare module 'draft-js/DraftEditorBlock.react' {
  declare module.exports: any;
}

declare module 'draft-js/DraftEditorCommand' {
  declare module.exports: any;
}

declare module 'draft-js/DraftEditorCompositionHandler' {
  declare module.exports: any;
}

declare module 'draft-js/DraftEditorContents.react' {
  declare module.exports: any;
}

declare module 'draft-js/DraftEditorDragHandler' {
  declare module.exports: any;
}

declare module 'draft-js/DraftEditorEditHandler' {
  declare module.exports: any;
}

declare module 'draft-js/DraftEditorLeaf.react' {
  declare module.exports: any;
}

declare module 'draft-js/DraftEditorModes' {
  declare module.exports: any;
}

declare module 'draft-js/DraftEditorPlaceholder.react' {
  declare module.exports: any;
}

declare module 'draft-js/DraftEditorProps' {
  declare module.exports: any;
}

declare module 'draft-js/DraftEditorTextNode.react' {
  declare module.exports: any;
}

declare module 'draft-js/DraftEntity' {
  declare module.exports: any;
}

declare module 'draft-js/DraftEntityInstance' {
  declare module.exports: any;
}

declare module 'draft-js/DraftEntityMutability' {
  declare module.exports: any;
}

declare module 'draft-js/DraftEntitySegments' {
  declare module.exports: any;
}

declare module 'draft-js/DraftEntityType' {
  declare module.exports: any;
}

declare module 'draft-js/DraftHandleValue' {
  declare module.exports: any;
}

declare module 'draft-js/DraftInlineStyle' {
  declare module.exports: any;
}

declare module 'draft-js/DraftModifier' {
  declare module.exports: any;
}

declare module 'draft-js/DraftOffsetKey' {
  declare module.exports: any;
}

declare module 'draft-js/DraftOffsetKeyPath' {
  declare module.exports: any;
}

declare module 'draft-js/DraftPasteProcessor' {
  declare module.exports: any;
}

declare module 'draft-js/DraftRange' {
  declare module.exports: any;
}

declare module 'draft-js/DraftRemovableWord' {
  declare module.exports: any;
}

declare module 'draft-js/DraftRemovalDirection' {
  declare module.exports: any;
}

declare module 'draft-js/DraftScrollPosition' {
  declare module.exports: any;
}

declare module 'draft-js/DraftStringKey' {
  declare module.exports: any;
}

declare module 'draft-js/DraftTextAlignment' {
  declare module.exports: any;
}

declare module 'draft-js/editOnBeforeInput' {
  declare module.exports: any;
}

declare module 'draft-js/editOnBlur' {
  declare module.exports: any;
}

declare module 'draft-js/editOnCompositionStart' {
  declare module.exports: any;
}

declare module 'draft-js/editOnCopy' {
  declare module.exports: any;
}

declare module 'draft-js/editOnCut' {
  declare module.exports: any;
}

declare module 'draft-js/editOnDragOver' {
  declare module.exports: any;
}

declare module 'draft-js/editOnDragStart' {
  declare module.exports: any;
}

declare module 'draft-js/editOnFocus' {
  declare module.exports: any;
}

declare module 'draft-js/editOnInput' {
  declare module.exports: any;
}

declare module 'draft-js/editOnKeyDown' {
  declare module.exports: any;
}

declare module 'draft-js/editOnPaste' {
  declare module.exports: any;
}

declare module 'draft-js/editOnSelect' {
  declare module.exports: any;
}

declare module 'draft-js/EditorBidiService' {
  declare module.exports: any;
}

declare module 'draft-js/EditorChangeType' {
  declare module.exports: any;
}

declare module 'draft-js/EditorState' {
  declare module.exports: any;
}

declare module 'draft-js/EditorStateCreationConfig' {
  declare module.exports: any;
}

declare module 'draft-js/encodeEntityRanges' {
  declare module.exports: any;
}

declare module 'draft-js/encodeInlineStyleRanges' {
  declare module.exports: any;
}

declare module 'draft-js/EntityRange' {
  declare module.exports: any;
}

declare module 'draft-js/expandRangeToStartOfLine' {
  declare module.exports: any;
}

declare module 'draft-js/findAncestorOffsetKey' {
  declare module.exports: any;
}

declare module 'draft-js/findRangesImmutable' {
  declare module.exports: any;
}

declare module 'draft-js/generateRandomKey' {
  declare module.exports: any;
}

declare module 'draft-js/getCharacterRemovalRange' {
  declare module.exports: any;
}

declare module 'draft-js/getContentStateFragment' {
  declare module.exports: any;
}

declare module 'draft-js/getDefaultKeyBinding' {
  declare module.exports: any;
}

declare module 'draft-js/getDraftEditorSelection' {
  declare module.exports: any;
}

declare module 'draft-js/getDraftEditorSelectionWithNodes' {
  declare module.exports: any;
}

declare module 'draft-js/getEntityKeyForSelection' {
  declare module.exports: any;
}

declare module 'draft-js/getFragmentFromSelection' {
  declare module.exports: any;
}

declare module 'draft-js/getRangeBoundingClientRect' {
  declare module.exports: any;
}

declare module 'draft-js/getRangeClientRects' {
  declare module.exports: any;
}

declare module 'draft-js/getRangesForDraftEntity' {
  declare module.exports: any;
}

declare module 'draft-js/getSafeBodyFromHTML' {
  declare module.exports: any;
}

declare module 'draft-js/getSampleStateForTesting' {
  declare module.exports: any;
}

declare module 'draft-js/getSelectionOffsetKeyForNode' {
  declare module.exports: any;
}

declare module 'draft-js/getTextAfterNearestEntity' {
  declare module.exports: any;
}

declare module 'draft-js/getTextContentFromFiles' {
  declare module.exports: any;
}

declare module 'draft-js/getUpdatedSelectionState' {
  declare module.exports: any;
}

declare module 'draft-js/getVisibleSelectionRect' {
  declare module.exports: any;
}

declare module 'draft-js/InlineStyleRange' {
  declare module.exports: any;
}

declare module 'draft-js/insertFragmentIntoContentState' {
  declare module.exports: any;
}

declare module 'draft-js/insertIntoList' {
  declare module.exports: any;
}

declare module 'draft-js/insertTextIntoContentState' {
  declare module.exports: any;
}

declare module 'draft-js/isEventHandled' {
  declare module.exports: any;
}

declare module 'draft-js/isSelectionAtLeafStart' {
  declare module.exports: any;
}

declare module 'draft-js/isSoftNewlineEvent' {
  declare module.exports: any;
}

declare module 'draft-js/KeyBindingUtil' {
  declare module.exports: any;
}

declare module 'draft-js/keyCommandBackspaceToStartOfLine' {
  declare module.exports: any;
}

declare module 'draft-js/keyCommandBackspaceWord' {
  declare module.exports: any;
}

declare module 'draft-js/keyCommandDeleteWord' {
  declare module.exports: any;
}

declare module 'draft-js/keyCommandInsertNewline' {
  declare module.exports: any;
}

declare module 'draft-js/keyCommandMoveSelectionToEndOfBlock' {
  declare module.exports: any;
}

declare module 'draft-js/keyCommandMoveSelectionToStartOfBlock' {
  declare module.exports: any;
}

declare module 'draft-js/keyCommandPlainBackspace' {
  declare module.exports: any;
}

declare module 'draft-js/keyCommandPlainDelete' {
  declare module.exports: any;
}

declare module 'draft-js/keyCommandTransposeCharacters' {
  declare module.exports: any;
}

declare module 'draft-js/keyCommandUndo' {
  declare module.exports: any;
}

declare module 'draft-js/modifyBlockForContentState' {
  declare module.exports: any;
}

declare module 'draft-js/moveSelectionBackward' {
  declare module.exports: any;
}

declare module 'draft-js/moveSelectionForward' {
  declare module.exports: any;
}

declare module 'draft-js/RawDraftContentBlock' {
  declare module.exports: any;
}

declare module 'draft-js/RawDraftContentState' {
  declare module.exports: any;
}

declare module 'draft-js/RawDraftEntity' {
  declare module.exports: any;
}

declare module 'draft-js/removeEntitiesAtEdges' {
  declare module.exports: any;
}

declare module 'draft-js/removeRangeFromContentState' {
  declare module.exports: any;
}

declare module 'draft-js/removeTextWithStrategy' {
  declare module.exports: any;
}

declare module 'draft-js/RichTextEditorUtil' {
  declare module.exports: any;
}

declare module 'draft-js/SampleDraftInlineStyle' {
  declare module.exports: any;
}

declare module 'draft-js/sanitizeDraftText' {
  declare module.exports: any;
}

declare module 'draft-js/SecondaryClipboard' {
  declare module.exports: any;
}

declare module 'draft-js/SelectionState' {
  declare module.exports: any;
}

declare module 'draft-js/setDraftEditorSelection' {
  declare module.exports: any;
}

declare module 'draft-js/splitBlockInContentState' {
  declare module.exports: any;
}

declare module 'draft-js/splitTextIntoTextBlocks' {
  declare module.exports: any;
}

// Filename aliases
declare module 'draft-js/Draft.js' {
  declare module.exports: $Exports<'draft-js/Draft'>;
}
declare module 'draft-js/Draft.min.js' {
  declare module.exports: $Exports<'draft-js/Draft.min'>;
}
declare module 'draft-js/adjustBlockDepthForContentState.js' {
  declare module.exports: $Exports<'draft-js/adjustBlockDepthForContentState'>;
}
declare module 'draft-js/applyEntityToContentBlock.js' {
  declare module.exports: $Exports<'draft-js/applyEntityToContentBlock'>;
}
declare module 'draft-js/applyEntityToContentState.js' {
  declare module.exports: $Exports<'draft-js/applyEntityToContentState'>;
}
declare module 'draft-js/AtomicBlockUtils.js' {
  declare module.exports: $Exports<'draft-js/AtomicBlockUtils'>;
}
declare module 'draft-js/BlockMap.js' {
  declare module.exports: $Exports<'draft-js/BlockMap'>;
}
declare module 'draft-js/BlockMapBuilder.js' {
  declare module.exports: $Exports<'draft-js/BlockMapBuilder'>;
}
declare module 'draft-js/BlockTree.js' {
  declare module.exports: $Exports<'draft-js/BlockTree'>;
}
declare module 'draft-js/CharacterMetadata.js' {
  declare module.exports: $Exports<'draft-js/CharacterMetadata'>;
}
declare module 'draft-js/ComposedEntityMutability.js' {
  declare module.exports: $Exports<'draft-js/ComposedEntityMutability'>;
}
declare module 'draft-js/ComposedEntityType.js' {
  declare module.exports: $Exports<'draft-js/ComposedEntityType'>;
}
declare module 'draft-js/CompositeDraftDecorator.js' {
  declare module.exports: $Exports<'draft-js/CompositeDraftDecorator'>;
}
declare module 'draft-js/ContentBlock.js' {
  declare module.exports: $Exports<'draft-js/ContentBlock'>;
}
declare module 'draft-js/ContentState.js' {
  declare module.exports: $Exports<'draft-js/ContentState'>;
}
declare module 'draft-js/ContentStateInlineStyle.js' {
  declare module.exports: $Exports<'draft-js/ContentStateInlineStyle'>;
}
declare module 'draft-js/convertFromDraftStateToRaw.js' {
  declare module.exports: $Exports<'draft-js/convertFromDraftStateToRaw'>;
}
declare module 'draft-js/convertFromHTMLToContentBlocks.js' {
  declare module.exports: $Exports<'draft-js/convertFromHTMLToContentBlocks'>;
}
declare module 'draft-js/convertFromRawToDraftState.js' {
  declare module.exports: $Exports<'draft-js/convertFromRawToDraftState'>;
}
declare module 'draft-js/createCharacterList.js' {
  declare module.exports: $Exports<'draft-js/createCharacterList'>;
}
declare module 'draft-js/decodeEntityRanges.js' {
  declare module.exports: $Exports<'draft-js/decodeEntityRanges'>;
}
declare module 'draft-js/decodeInlineStyleRanges.js' {
  declare module.exports: $Exports<'draft-js/decodeInlineStyleRanges'>;
}
declare module 'draft-js/DefaultDraftBlockRenderMap.js' {
  declare module.exports: $Exports<'draft-js/DefaultDraftBlockRenderMap'>;
}
declare module 'draft-js/DefaultDraftInlineStyle.js' {
  declare module.exports: $Exports<'draft-js/DefaultDraftInlineStyle'>;
}
declare module 'draft-js/DOMDerivedSelection.js' {
  declare module.exports: $Exports<'draft-js/DOMDerivedSelection'>;
}
declare module 'draft-js/Draft.js' {
  declare module.exports: $Exports<'draft-js/Draft'>;
}
declare module 'draft-js/DraftBlockRenderConfig.js' {
  declare module.exports: $Exports<'draft-js/DraftBlockRenderConfig'>;
}
declare module 'draft-js/DraftBlockRenderMap.js' {
  declare module.exports: $Exports<'draft-js/DraftBlockRenderMap'>;
}
declare module 'draft-js/DraftBlockTag.js' {
  declare module.exports: $Exports<'draft-js/DraftBlockTag'>;
}
declare module 'draft-js/DraftBlockType.js' {
  declare module.exports: $Exports<'draft-js/DraftBlockType'>;
}
declare module 'draft-js/DraftDecorator.js' {
  declare module.exports: $Exports<'draft-js/DraftDecorator'>;
}
declare module 'draft-js/DraftDecoratorType.js' {
  declare module.exports: $Exports<'draft-js/DraftDecoratorType'>;
}
declare module 'draft-js/DraftDragType.js' {
  declare module.exports: $Exports<'draft-js/DraftDragType'>;
}
declare module 'draft-js/DraftEditor.react.js' {
  declare module.exports: $Exports<'draft-js/DraftEditor.react'>;
}
declare module 'draft-js/DraftEditorBlock.react.js' {
  declare module.exports: $Exports<'draft-js/DraftEditorBlock.react'>;
}
declare module 'draft-js/DraftEditorCommand.js' {
  declare module.exports: $Exports<'draft-js/DraftEditorCommand'>;
}
declare module 'draft-js/DraftEditorCompositionHandler.js' {
  declare module.exports: $Exports<'draft-js/DraftEditorCompositionHandler'>;
}
declare module 'draft-js/DraftEditorContents.react.js' {
  declare module.exports: $Exports<'draft-js/DraftEditorContents.react'>;
}
declare module 'draft-js/DraftEditorDragHandler.js' {
  declare module.exports: $Exports<'draft-js/DraftEditorDragHandler'>;
}
declare module 'draft-js/DraftEditorEditHandler.js' {
  declare module.exports: $Exports<'draft-js/DraftEditorEditHandler'>;
}
declare module 'draft-js/DraftEditorLeaf.react.js' {
  declare module.exports: $Exports<'draft-js/DraftEditorLeaf.react'>;
}
declare module 'draft-js/DraftEditorModes.js' {
  declare module.exports: $Exports<'draft-js/DraftEditorModes'>;
}
declare module 'draft-js/DraftEditorPlaceholder.react.js' {
  declare module.exports: $Exports<'draft-js/DraftEditorPlaceholder.react'>;
}
declare module 'draft-js/DraftEditorProps.js' {
  declare module.exports: $Exports<'draft-js/DraftEditorProps'>;
}
declare module 'draft-js/DraftEditorTextNode.react.js' {
  declare module.exports: $Exports<'draft-js/DraftEditorTextNode.react'>;
}
declare module 'draft-js/DraftEntity.js' {
  declare module.exports: $Exports<'draft-js/DraftEntity'>;
}
declare module 'draft-js/DraftEntityInstance.js' {
  declare module.exports: $Exports<'draft-js/DraftEntityInstance'>;
}
declare module 'draft-js/DraftEntityMutability.js' {
  declare module.exports: $Exports<'draft-js/DraftEntityMutability'>;
}
declare module 'draft-js/DraftEntitySegments.js' {
  declare module.exports: $Exports<'draft-js/DraftEntitySegments'>;
}
declare module 'draft-js/DraftEntityType.js' {
  declare module.exports: $Exports<'draft-js/DraftEntityType'>;
}
declare module 'draft-js/DraftHandleValue.js' {
  declare module.exports: $Exports<'draft-js/DraftHandleValue'>;
}
declare module 'draft-js/DraftInlineStyle.js' {
  declare module.exports: $Exports<'draft-js/DraftInlineStyle'>;
}
declare module 'draft-js/DraftModifier.js' {
  declare module.exports: $Exports<'draft-js/DraftModifier'>;
}
declare module 'draft-js/DraftOffsetKey.js' {
  declare module.exports: $Exports<'draft-js/DraftOffsetKey'>;
}
declare module 'draft-js/DraftOffsetKeyPath.js' {
  declare module.exports: $Exports<'draft-js/DraftOffsetKeyPath'>;
}
declare module 'draft-js/DraftPasteProcessor.js' {
  declare module.exports: $Exports<'draft-js/DraftPasteProcessor'>;
}
declare module 'draft-js/DraftRange.js' {
  declare module.exports: $Exports<'draft-js/DraftRange'>;
}
declare module 'draft-js/DraftRemovableWord.js' {
  declare module.exports: $Exports<'draft-js/DraftRemovableWord'>;
}
declare module 'draft-js/DraftRemovalDirection.js' {
  declare module.exports: $Exports<'draft-js/DraftRemovalDirection'>;
}
declare module 'draft-js/DraftScrollPosition.js' {
  declare module.exports: $Exports<'draft-js/DraftScrollPosition'>;
}
declare module 'draft-js/DraftStringKey.js' {
  declare module.exports: $Exports<'draft-js/DraftStringKey'>;
}
declare module 'draft-js/DraftTextAlignment.js' {
  declare module.exports: $Exports<'draft-js/DraftTextAlignment'>;
}
declare module 'draft-js/editOnBeforeInput.js' {
  declare module.exports: $Exports<'draft-js/editOnBeforeInput'>;
}
declare module 'draft-js/editOnBlur.js' {
  declare module.exports: $Exports<'draft-js/editOnBlur'>;
}
declare module 'draft-js/editOnCompositionStart.js' {
  declare module.exports: $Exports<'draft-js/editOnCompositionStart'>;
}
declare module 'draft-js/editOnCopy.js' {
  declare module.exports: $Exports<'draft-js/editOnCopy'>;
}
declare module 'draft-js/editOnCut.js' {
  declare module.exports: $Exports<'draft-js/editOnCut'>;
}
declare module 'draft-js/editOnDragOver.js' {
  declare module.exports: $Exports<'draft-js/editOnDragOver'>;
}
declare module 'draft-js/editOnDragStart.js' {
  declare module.exports: $Exports<'draft-js/editOnDragStart'>;
}
declare module 'draft-js/editOnFocus.js' {
  declare module.exports: $Exports<'draft-js/editOnFocus'>;
}
declare module 'draft-js/editOnInput.js' {
  declare module.exports: $Exports<'draft-js/editOnInput'>;
}
declare module 'draft-js/editOnKeyDown.js' {
  declare module.exports: $Exports<'draft-js/editOnKeyDown'>;
}
declare module 'draft-js/editOnPaste.js' {
  declare module.exports: $Exports<'draft-js/editOnPaste'>;
}
declare module 'draft-js/editOnSelect.js' {
  declare module.exports: $Exports<'draft-js/editOnSelect'>;
}
declare module 'draft-js/EditorBidiService.js' {
  declare module.exports: $Exports<'draft-js/EditorBidiService'>;
}
declare module 'draft-js/EditorChangeType.js' {
  declare module.exports: $Exports<'draft-js/EditorChangeType'>;
}
declare module 'draft-js/EditorState.js' {
  declare module.exports: $Exports<'draft-js/EditorState'>;
}
declare module 'draft-js/EditorStateCreationConfig.js' {
  declare module.exports: $Exports<'draft-js/EditorStateCreationConfig'>;
}
declare module 'draft-js/encodeEntityRanges.js' {
  declare module.exports: $Exports<'draft-js/encodeEntityRanges'>;
}
declare module 'draft-js/encodeInlineStyleRanges.js' {
  declare module.exports: $Exports<'draft-js/encodeInlineStyleRanges'>;
}
declare module 'draft-js/EntityRange.js' {
  declare module.exports: $Exports<'draft-js/EntityRange'>;
}
declare module 'draft-js/expandRangeToStartOfLine.js' {
  declare module.exports: $Exports<'draft-js/expandRangeToStartOfLine'>;
}
declare module 'draft-js/findAncestorOffsetKey.js' {
  declare module.exports: $Exports<'draft-js/findAncestorOffsetKey'>;
}
declare module 'draft-js/findRangesImmutable.js' {
  declare module.exports: $Exports<'draft-js/findRangesImmutable'>;
}
declare module 'draft-js/generateRandomKey.js' {
  declare module.exports: $Exports<'draft-js/generateRandomKey'>;
}
declare module 'draft-js/getCharacterRemovalRange.js' {
  declare module.exports: $Exports<'draft-js/getCharacterRemovalRange'>;
}
declare module 'draft-js/getContentStateFragment.js' {
  declare module.exports: $Exports<'draft-js/getContentStateFragment'>;
}
declare module 'draft-js/getDefaultKeyBinding.js' {
  declare module.exports: $Exports<'draft-js/getDefaultKeyBinding'>;
}
declare module 'draft-js/getDraftEditorSelection.js' {
  declare module.exports: $Exports<'draft-js/getDraftEditorSelection'>;
}
declare module 'draft-js/getDraftEditorSelectionWithNodes.js' {
  declare module.exports: $Exports<'draft-js/getDraftEditorSelectionWithNodes'>;
}
declare module 'draft-js/getEntityKeyForSelection.js' {
  declare module.exports: $Exports<'draft-js/getEntityKeyForSelection'>;
}
declare module 'draft-js/getFragmentFromSelection.js' {
  declare module.exports: $Exports<'draft-js/getFragmentFromSelection'>;
}
declare module 'draft-js/getRangeBoundingClientRect.js' {
  declare module.exports: $Exports<'draft-js/getRangeBoundingClientRect'>;
}
declare module 'draft-js/getRangeClientRects.js' {
  declare module.exports: $Exports<'draft-js/getRangeClientRects'>;
}
declare module 'draft-js/getRangesForDraftEntity.js' {
  declare module.exports: $Exports<'draft-js/getRangesForDraftEntity'>;
}
declare module 'draft-js/getSafeBodyFromHTML.js' {
  declare module.exports: $Exports<'draft-js/getSafeBodyFromHTML'>;
}
declare module 'draft-js/getSampleStateForTesting.js' {
  declare module.exports: $Exports<'draft-js/getSampleStateForTesting'>;
}
declare module 'draft-js/getSelectionOffsetKeyForNode.js' {
  declare module.exports: $Exports<'draft-js/getSelectionOffsetKeyForNode'>;
}
declare module 'draft-js/getTextAfterNearestEntity.js' {
  declare module.exports: $Exports<'draft-js/getTextAfterNearestEntity'>;
}
declare module 'draft-js/getTextContentFromFiles.js' {
  declare module.exports: $Exports<'draft-js/getTextContentFromFiles'>;
}
declare module 'draft-js/getUpdatedSelectionState.js' {
  declare module.exports: $Exports<'draft-js/getUpdatedSelectionState'>;
}
declare module 'draft-js/getVisibleSelectionRect.js' {
  declare module.exports: $Exports<'draft-js/getVisibleSelectionRect'>;
}
declare module 'draft-js/InlineStyleRange.js' {
  declare module.exports: $Exports<'draft-js/InlineStyleRange'>;
}
declare module 'draft-js/insertFragmentIntoContentState.js' {
  declare module.exports: $Exports<'draft-js/insertFragmentIntoContentState'>;
}
declare module 'draft-js/insertIntoList.js' {
  declare module.exports: $Exports<'draft-js/insertIntoList'>;
}
declare module 'draft-js/insertTextIntoContentState.js' {
  declare module.exports: $Exports<'draft-js/insertTextIntoContentState'>;
}
declare module 'draft-js/isEventHandled.js' {
  declare module.exports: $Exports<'draft-js/isEventHandled'>;
}
declare module 'draft-js/isSelectionAtLeafStart.js' {
  declare module.exports: $Exports<'draft-js/isSelectionAtLeafStart'>;
}
declare module 'draft-js/isSoftNewlineEvent.js' {
  declare module.exports: $Exports<'draft-js/isSoftNewlineEvent'>;
}
declare module 'draft-js/KeyBindingUtil.js' {
  declare module.exports: $Exports<'draft-js/KeyBindingUtil'>;
}
declare module 'draft-js/keyCommandBackspaceToStartOfLine.js' {
  declare module.exports: $Exports<'draft-js/keyCommandBackspaceToStartOfLine'>;
}
declare module 'draft-js/keyCommandBackspaceWord.js' {
  declare module.exports: $Exports<'draft-js/keyCommandBackspaceWord'>;
}
declare module 'draft-js/keyCommandDeleteWord.js' {
  declare module.exports: $Exports<'draft-js/keyCommandDeleteWord'>;
}
declare module 'draft-js/keyCommandInsertNewline.js' {
  declare module.exports: $Exports<'draft-js/keyCommandInsertNewline'>;
}
declare module 'draft-js/keyCommandMoveSelectionToEndOfBlock.js' {
  declare module.exports: $Exports<'draft-js/keyCommandMoveSelectionToEndOfBlock'>;
}
declare module 'draft-js/keyCommandMoveSelectionToStartOfBlock.js' {
  declare module.exports: $Exports<'draft-js/keyCommandMoveSelectionToStartOfBlock'>;
}
declare module 'draft-js/keyCommandPlainBackspace.js' {
  declare module.exports: $Exports<'draft-js/keyCommandPlainBackspace'>;
}
declare module 'draft-js/keyCommandPlainDelete.js' {
  declare module.exports: $Exports<'draft-js/keyCommandPlainDelete'>;
}
declare module 'draft-js/keyCommandTransposeCharacters.js' {
  declare module.exports: $Exports<'draft-js/keyCommandTransposeCharacters'>;
}
declare module 'draft-js/keyCommandUndo.js' {
  declare module.exports: $Exports<'draft-js/keyCommandUndo'>;
}
declare module 'draft-js/modifyBlockForContentState.js' {
  declare module.exports: $Exports<'draft-js/modifyBlockForContentState'>;
}
declare module 'draft-js/moveSelectionBackward.js' {
  declare module.exports: $Exports<'draft-js/moveSelectionBackward'>;
}
declare module 'draft-js/moveSelectionForward.js' {
  declare module.exports: $Exports<'draft-js/moveSelectionForward'>;
}
declare module 'draft-js/RawDraftContentBlock.js' {
  declare module.exports: $Exports<'draft-js/RawDraftContentBlock'>;
}
declare module 'draft-js/RawDraftContentState.js' {
  declare module.exports: $Exports<'draft-js/RawDraftContentState'>;
}
declare module 'draft-js/RawDraftEntity.js' {
  declare module.exports: $Exports<'draft-js/RawDraftEntity'>;
}
declare module 'draft-js/removeEntitiesAtEdges.js' {
  declare module.exports: $Exports<'draft-js/removeEntitiesAtEdges'>;
}
declare module 'draft-js/removeRangeFromContentState.js' {
  declare module.exports: $Exports<'draft-js/removeRangeFromContentState'>;
}
declare module 'draft-js/removeTextWithStrategy.js' {
  declare module.exports: $Exports<'draft-js/removeTextWithStrategy'>;
}
declare module 'draft-js/RichTextEditorUtil.js' {
  declare module.exports: $Exports<'draft-js/RichTextEditorUtil'>;
}
declare module 'draft-js/SampleDraftInlineStyle.js' {
  declare module.exports: $Exports<'draft-js/SampleDraftInlineStyle'>;
}
declare module 'draft-js/sanitizeDraftText.js' {
  declare module.exports: $Exports<'draft-js/sanitizeDraftText'>;
}
declare module 'draft-js/SecondaryClipboard.js' {
  declare module.exports: $Exports<'draft-js/SecondaryClipboard'>;
}
declare module 'draft-js/SelectionState.js' {
  declare module.exports: $Exports<'draft-js/SelectionState'>;
}
declare module 'draft-js/setDraftEditorSelection.js' {
  declare module.exports: $Exports<'draft-js/setDraftEditorSelection'>;
}
declare module 'draft-js/splitBlockInContentState.js' {
  declare module.exports: $Exports<'draft-js/splitBlockInContentState'>;
}
declare module 'draft-js/splitTextIntoTextBlocks.js' {
  declare module.exports: $Exports<'draft-js/splitTextIntoTextBlocks'>;
}
