// flow-typed signature: 8ac94b157ce82ddbfc76be5fa5b82d9f
// flow-typed version: <<STUB>>/draft-js-export-html_v0.4.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'draft-js-export-html'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'draft-js-export-html' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'draft-js-export-html/combineOrderedStyles' {
  declare module.exports: any;
}

declare module 'draft-js-export-html/normalizeAttributes' {
  declare module.exports: any;
}

declare module 'draft-js-export-html/styleToCSS' {
  declare module.exports: any;
}

declare module 'draft-js-export-html/main' {
  declare module.exports: any;
}

declare module 'draft-js-export-html/stateToHTML' {
  declare module.exports: any;
}

// Filename aliases
declare module 'draft-js-export-html/combineOrderedStyles.js' {
  declare module.exports: $Exports<'draft-js-export-html/combineOrderedStyles'>;
}
declare module 'draft-js-export-html/normalizeAttributes.js' {
  declare module.exports: $Exports<'draft-js-export-html/normalizeAttributes'>;
}
declare module 'draft-js-export-html/styleToCSS.js' {
  declare module.exports: $Exports<'draft-js-export-html/styleToCSS'>;
}
declare module 'draft-js-export-html/main.js' {
  declare module.exports: $Exports<'draft-js-export-html/main'>;
}
declare module 'draft-js-export-html/stateToHTML.js' {
  declare module.exports: $Exports<'draft-js-export-html/stateToHTML'>;
}
