// flow-typed signature: 68cf95306f2e65f5a2d90f3ddd30ad45
// flow-typed version: <<STUB>>/enzyme-to-json_v^1.1.5/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'enzyme-to-json'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'enzyme-to-json' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'enzyme-to-json/build/index' {
  declare module.exports: any;
}

declare module 'enzyme-to-json/build/mount' {
  declare module.exports: any;
}

declare module 'enzyme-to-json/build/render' {
  declare module.exports: any;
}

declare module 'enzyme-to-json/build/shallow' {
  declare module.exports: any;
}

// Filename aliases
declare module 'enzyme-to-json/build/index.js' {
  declare module.exports: $Exports<'enzyme-to-json/build/index'>;
}
declare module 'enzyme-to-json/build/mount.js' {
  declare module.exports: $Exports<'enzyme-to-json/build/mount'>;
}
declare module 'enzyme-to-json/build/render.js' {
  declare module.exports: $Exports<'enzyme-to-json/build/render'>;
}
declare module 'enzyme-to-json/build/shallow.js' {
  declare module.exports: $Exports<'enzyme-to-json/build/shallow'>;
}
