// flow-typed signature: 51b9df7e2c9868ae71baa516fa7b9352
// flow-typed version: <<STUB>>/humps_v^2.0.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'humps'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'humps' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'humps/humps' {
  declare module.exports: any;
}

declare module 'humps/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'humps/humps.js' {
  declare module.exports: $Exports<'humps/humps'>;
}
declare module 'humps/test/test.js' {
  declare module.exports: $Exports<'humps/test/test'>;
}
