// flow-typed signature: ff7415bde354bbdc851b6d4685e5cf2b
// flow-typed version: <<STUB>>/superagent_v2.3.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'superagent'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'superagent' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'superagent/client' {
  declare module.exports: any;
}

declare module 'superagent/is-object' {
  declare module.exports: any;
}

declare module 'superagent/agent' {
  declare module.exports: any;
}

declare module 'superagent/image' {
  declare module.exports: any;
}

declare module 'superagent/json' {
  declare module.exports: any;
}

declare module 'superagent/text' {
  declare module.exports: any;
}

declare module 'superagent/urlencoded' {
  declare module.exports: any;
}

declare module 'superagent/part' {
  declare module.exports: any;
}

declare module 'superagent/response' {
  declare module.exports: any;
}

declare module 'superagent/utils' {
  declare module.exports: any;
}

declare module 'superagent/request-base' {
  declare module.exports: any;
}

declare module 'superagent/request' {
  declare module.exports: any;
}

declare module 'superagent/superagent' {
  declare module.exports: any;
}

// Filename aliases
declare module 'superagent/client.js' {
  declare module.exports: $Exports<'superagent/client'>;
}
declare module 'superagent/is-object.js' {
  declare module.exports: $Exports<'superagent/is-object'>;
}
declare module 'superagent/agent.js' {
  declare module.exports: $Exports<'superagent/agent'>;
}
declare module 'superagent/index' {
  declare module.exports: $Exports<'superagent'>;
}
declare module 'superagent/index.js' {
  declare module.exports: $Exports<'superagent'>;
}
declare module 'superagent/image.js' {
  declare module.exports: $Exports<'superagent/image'>;
}
declare module 'superagent/index' {
  declare module.exports: $Exports<'superagent'>;
}
declare module 'superagent/index.js' {
  declare module.exports: $Exports<'superagent'>;
}
declare module 'superagent/json.js' {
  declare module.exports: $Exports<'superagent/json'>;
}
declare module 'superagent/text.js' {
  declare module.exports: $Exports<'superagent/text'>;
}
declare module 'superagent/urlencoded.js' {
  declare module.exports: $Exports<'superagent/urlencoded'>;
}
declare module 'superagent/part.js' {
  declare module.exports: $Exports<'superagent/part'>;
}
declare module 'superagent/response.js' {
  declare module.exports: $Exports<'superagent/response'>;
}
declare module 'superagent/utils.js' {
  declare module.exports: $Exports<'superagent/utils'>;
}
declare module 'superagent/request-base.js' {
  declare module.exports: $Exports<'superagent/request-base'>;
}
declare module 'superagent/request.js' {
  declare module.exports: $Exports<'superagent/request'>;
}
declare module 'superagent/superagent.js' {
  declare module.exports: $Exports<'superagent/superagent'>;
}
