
export const GET_MY_PROFILE_REQUEST = 'GET_MY_PROFILE_REQUEST';
export const GET_MY_PROFILE_SUCCESS = 'GET_MY_PROFILE_SUCCESS';
export const GET_MY_PROFILE_FAIL = 'GET_MY_PROFILE_FAIL';

export const PUBLIC_PROFILE_REQUEST = 'PUBLIC_PROFILE_REQUEST';
export const PUBLIC_PROFILE_SUCCESS = 'PUBLIC_PROFILE_SUCCESS';
export const PUBLIC_PROFILE_FAIL = 'PUBLIC_PROFILE_FAIL';
