// Globals
// -----------------
export const DONE_LOADING = 'DONE_LOADING';
export const LOAD_SETTINGS = 'LOAD_SETTINGS';
export const LOAD_SETTINGS_SUCCESS = 'LOAD_SETTINGS_SUCCESS';
export const LOAD_SETTINGS_FAILURE = 'LOAD_SETTINGS_FAILURE';
export const SAVE_SETUP_REQUEST = 'SAVE_SETUP_REQUEST';
export const SAVE_SETUP_SUCCESS = 'SAVE_SETUP_SUCCESS';
export const SAVE_SETUP_FAIL = 'SAVE_SETUP_FAIL';
export const UPDATE_SETTINGS_REQUEST = 'UPDATE_SETTINGS_REQUEST';
export const UPDATE_SETTINGS_SUCCESS = 'UPDATE_SETTINGS_SUCCESS';
export const UPDATE_SETTINGS_FAILURE = 'UPDATE_SETTINGS_FAILURE';

// Notifications
// -----------------
export const NOTIFICATION_SEND = 'NOTIFICATION_SEND';
export const NOTIFICATION_DISMISS = 'NOTIFICATION_DISMISS';
export const NOTIFICATION_CLEAR = 'NOTIFICATION_CLEAR';

// Posts
// -----------------
export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE';
export const LOAD_POST_REQUEST = 'LOAD_POST_REQUEST';
export const LOAD_POST_SUCCESS = 'LOAD_POST_SUCCESS';
export const LOAD_POST_FAILURE = 'LOAD_POST_FAILURE';
export const UPDATE_POST_REQUEST = 'UPDATE_POST_REQUEST';
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS';
export const UPDATE_POST_FAILURE = 'UPDATE_POST_FAILURE';
export const SELECT_POST = 'SELECT_POST';
export const SELECT_POST_SUCCESS = 'SELECT_POST_SUCCESS';
export const SELECT_POST_FAIL = 'SELECT_POST_FAIL';
export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_FAIL = 'CREATE_POST_FAIL';
export const CLEAR_CURRENT_POST = 'CLEAR_CURRENT_POST';

// Auth
// -----------------
export const LOGIN_REQUEST = 'AUTH/LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'AUTH/LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'AUTH/LOGIN_FAILURE';
export const LOGOUT_USER = 'AUTH/LOGOUT_USER';
export const LOGOUT_USER_FAIL = 'AUTH/LOGOUT_USER_FAIL';
export const CHECK_AUTH_REQUEST = 'AUTH/CHECK_AUTH_REQUEST';
export const CHECK_AUTH_SUCCESS = 'AUTH/CHECK_AUTH_SUCCESS';
export const CHECK_AUTH_FAILURE = 'AUTH/CHECK_AUTH_FAILURE';

// Account
// -----------------
export const CREATE_ACCOUNT_REQUEST = 'AUTH/CREATE_ACCOUNT_REQUEST';
export const CREATE_ACCOUNT_SUCCESS = 'AUTH/CREATE_ACCOUNT_SUCCESS';
export const CREATE_ACCOUNT_FAILURE = 'AUTH/CREATE_ACCOUNT_FAILURE';
export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE';
export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';

// Media
// -----------------
export const GET_MEDIA_REQUEST = 'GET_MEDIA_REQUEST';
export const GET_MEDIA_SUCCESS = 'GET_MEDIA_SUCCESS';
export const GET_MEDIA_FAIL = 'GET_MEDIA_FAIL';

export const UPLOAD_REQUEST = 'UPLOAD_REQUEST';
export const UPLOAD_SUCCESS = 'UPLOAD_SUCCESS';
export const UPLOAD_FAIL = 'UPLOAD_FAIL';

// Members
// -----------------
export const LOAD_MEMBERS_REQUEST = 'LOAD_MEMBERS_REQUEST';
export const LOAD_MEMBERS_SUCCESS = 'LOAD_MEMBERS_SUCCESS';
export const LOAD_MEMBERS_FAILURE = 'LOAD_MEMBERS_FAILURE';


export const LOAD_NAVIGATION_REQUEST = 'navigation/LOAD_NAVIGATION_REQUEST';
export const LOAD_NAVIGATION_SUCCESS = 'navigation/LOAD_NAVIGATION_SUCCESS';
export const LOAD_NAVIGATION_FAILURE = 'navigation/LOAD_NAVIGATION_FAILURE';

export const UPDATE_NAVIGATION_REQUEST = 'navigation/UPDATE_NAVIGATION_REQUEST';
export const UPDATE_NAVIGATION_SUCCESS = 'navigation/UPDATE_NAVIGATION_SUCCESS';
export const UPDATE_NAVIGATION_FAILURE = 'navigation/UPDATE_NAVIGATION_FAILURE';

// Profile
// -----------------
export const GET_MY_PROFILE_REQUEST = 'GET_MY_PROFILE_REQUEST';
export const GET_MY_PROFILE_SUCCESS = 'GET_MY_PROFILE_SUCCESS';
export const GET_MY_PROFILE_FAIL = 'GET_MY_PROFILE_FAIL';

export const PUBLIC_PROFILE_REQUEST = 'PUBLIC_PROFILE_REQUEST';
export const PUBLIC_PROFILE_SUCCESS = 'PUBLIC_PROFILE_SUCCESS';
export const PUBLIC_PROFILE_FAIL = 'PUBLIC_PROFILE_FAIL';

// Tags
// -----------------
export const LOAD_TAG_REQUEST = 'LOAD_TAG_REQUEST';
export const LOAD_TAG_SUCCESS = 'LOAD_TAG_SUCCESS';
export const LOAD_TAG_FAILURE = 'LOAD_TAG_FAILURE';
